- XXXX-template.md
- proposals/0001-simd-process.md
The current proposal process is as follows:
1. Discuss across core engineering about a proposed feature in Discord and/or
github issue(s).
2. Create a proposal document under
[docs/src/proposals](https://github.com/solana-labs/solana/tree/master/docs/src/proposals).
3. Review is done by core engineering + community members
4. PR Is pulled into `Accepted Design proposals` and live on [Solana
Docs](https://docs.solana.com/proposals/accepted-design-proposals)
5. If required, a `feature-gate` issue is created and kept up-to-date to track
the feature's activation.
6. If the proposal needs to be tweaked, submit a new PR and have the change
reviewed by the same group in step 3.
7. Once implementation is complete, submit a PR that moves the link from
`Accepted Design Proposals` to `Implemented …
> Add SIMD-0001: A process for improvements

- proposals/0001-simd-process.md
documentation should not refer to it as being there.
> The XXXX-template.md file is not in the proposals directory, so the

- proposals/0022-multi-stake.md
Proposal to create a new kind of stake account. The main use-case is to properly support single-validator stake pools for small stakers, but provides benefits to every staker.
> Add multistake proposal

- proposals/0007-access-policy.md
- proposals/0022-multi-stake.md
Fixing SIMDs that are failing the new linting CI. These SIMDs were created before the linting CI was pulled in
> fix: pre-linting CI errors

- XXXX-template.md
- proposals/0001-simd-process.md
While there is a possibility for some SIMDs to be updated in the future, I'd like those SIMDs to be directly noted as updatable. Otherwise we should write new SIMDs that `supercede` or `extend` previous SIMDs.
> Add living status, supercede, extends, and rfc 2119 recommendation to template

- .github/linter/customRules.ts
Aligns CI with the template by adding `supersedes` and `extends` to the optional metadata.
> fix custom ci for metadata

- proposals/0085-additional-fee-collector-constraints.md
Add SIMD for adding fee collector constraints
> SIMD-0085: Additional Fee Collector Constraints

- proposals/0093-disable-bpf-loader-instructions.md
Add disable bpf loader (V2) instructions simd
> SIMD-0093:  Disable bpf loader (V2) instructions 

- proposals/0096-reward-collected-priority-fee-in-entirety.md
Reward 100% of priority fee to validator.
> SIMD-0096: Reward full priority fee to validators

- proposals/0088-enable-core-bpf-programs.md
This proposal defines the concept of "Core BPF Programs" - programs which are essential to cluster operations but exist as BPF programs, rather than native built-in programs.
The proposal describes, in a general sense, how native programs are migrated to Core BPF, and defines the requirements for proposing a native program migration to Core BPF.
> SIMD-0088: Enable Core BPF Programs

- .github/linter/customRules.ts
- XXXX-template.md
Frontmatter to denote what SIMD another SIMD was superseded by was needed to make it easy to understand what SIMDs take precedent. Added the optional frontmatter to template + CI.
> add: superseded-by frontmatter

- proposals/0015-partitioned-epoch-reward-distribution.md
- proposals/0118-partitioned-epoch-reward-distribution.md
This SIMD supersedes SIMD-0015 with some new design elements.
I have begun by copying in the original SIMD so that the changes can be seen more easily in subsequent commits.
https://github.com/solana-foundation/solana-improvement-documents/pull/116 may be useful as a reference, as it describes the existing Labs implementation.
> SIMD-0118: Partitioned Epoch Rewards, amend/extend design

- proposals/0129-alt-bn128-simplified-error-code.md
Simplify the return error code for the family of Alt_BN128 syscalls: 
`sol_alt_bn128_group_op`, `sol_alt_bn128_compression` and `sol_poseidon`.
A single error code is sufficient, in line with all other syscalls.
Syscalls in Solana can return:
- Success, e.g. represented in Rust as `Ok(0)` or `Ok(SUCCESS)`
- Error to the program, e.g. represented in Rust as `Ok(1)`
- Fatal error to the VM, aborting the transaction, e.g. represented in Rust
as `Err(<something>)`
Most syscalls only have a single error code returned to the program, i.e. `Ok(1)`.
The family of Alt_BN128 syscalls, viceversa, has a richer set of error codes.
This proposal aims to simplify the error value for these syscalls, in line with
all the other syscalls, and simply return `Ok(1)` (in addition to fatal errors,
that are left …
> SIMD-0129: Alt_BN128 Syscalls - Simplified Error Code

- proposals/0133-syscall-get-epoch-stake.md
A syscall to retrieve a vote account's delegated stake for the current epoch.
Currently, on-chain programs have no knowledge of the current epoch's stake and
how much active stake is delegated to a certain vote account.
If this data was available for querying by on-chain programs, it would unblock
many use cases, such as validator governance and secondary consensus mechanisms,
that were previously not possible on Solana.
Additionally, this would enable the Feature Gate program defined in
[SIMD 0089](https://github.com/solana-foundation/solana-improvement-documents/pull/72) to tally vote account stake in
support for a pending feature gate.
> SIMD-0133: Syscall: Get Epoch Stake

- proposals/0083-relax-entry-constraints.md
- proposals/XXXX-relax-entry-constraints.md
The second in a series of SIMDs aimed at the relaxation of constraints blocking us from (potentially) having asynchronous execution.
This proposal does not lock Solana into moving towards asynchronous execution.
This proposal stands on its own to simplify the protocol and give more flexibility in implementation of block-production.
> SIMD-0083: Relax Entry Constraints

- proposals/0127-get-sysvar-syscall.md
This proposal outlines a new syscall interface for sysvars; one which can
retrieve dynamic ranges of sysvar data without fully copying the entire data
structure.
With a unified syscall interface to handle retrieval of sysvar data, many
existing syscalls will become obsolete, and the act of changing sysvar data
layouts or adding new sysvars will involve much less overhead.
Sysvars are special accounts that are implicitly modified by the runtime.
Certain sysvars are essential for operation of the network, and many others are
used by on-chain programs for a wide range of use cases.
The sysvar API should be completely consistent, available to all BPF programs,
and capable of more easily handling changes in the future. The syscall API for
sysvars should be designed to serve a wide range of …
> SIMD-0127: Syscall: Get-Sysvar

- proposals/0118-partitioned-epoch-reward-distribution.md
SIMD-0118 specifies a StakeError variant index that is already taken; this is just a typo due to miscounting (author may need a preschool refresher). This PR fixes the index.
This PR also updates the variant text to match the Agave implementation; this is not important to the spec, so I will revert if desired. But the updated text is more accurate, since the error will also be thrown during the calculation block.
> SIMD-0118: Update StakeError definition

- proposals/0088-enable-core-bpf-programs.md
During implementation of #88, Anza and Firedancer contributors discussed the 
benefits of using a buffer account to store the BPF implementation of a builtin 
program, rather than a deployed upgradeable program.
This protects builtin migration preparation from unexpected issues, such as 
those that may arise from attackers invoking the source program before it's 
moved in place of the target builtin.
Additionally, we wanted to take the opportunity to specify the **delayed
visibility slot** involved in migration.
Revise the SIMD to specify using buffer accounts as well as the one-slot delayed 
visibility during migration.
> Amend 0088 to use buffer account

- proposals/0084-disable-rent-fees-collection.md
Add simd for disable rent fees collection.
> SIMD-0084: Disable rent fees collection

- proposals/0089-programify-feature-gate-program.md
After further discussions with the Firedancer team around Core BPF programs,
we've decided these programs should all be upgraded using feature gates.
This amendment updates SIMD 0089 (Programify Feature Gate) to reflect this
agreement.
I've also removed the bit about first deploying a no-op program, since we wouldn't
be able to upgrade via keypair after performing the migration.
> Amend 0089: Update program upgrade process

- proposals/0133-syscall-get-epoch-stake.md
Amend SIMD 0133 - Syscall `GetEpochStake` - to support retrieval of the
_total cluster stake_, in addition to a vote account's stake, for the current
epoch.
The main change here is that a null pointer will allow callers to retrieve the
total cluster stake for the epoch.
A potential point of contention is going to be the designated compute usage
for retrieval of total stake.
cc @michaelh-laine
> Amend 0133: Support total cluster stake

- proposals/0152-precompiles.md
Define a unified behavior for precompiles, and highlight a few minor
changes to the existing precompiles to minimize differences.
Precompiles are special native programs designed to verify additional
transaction signatures.
They run without the VM and without loading any account, and they can access
data from other instructions, within the same transaction.
At the time of writing, two precompiles exist to verify Ed25519 and
Ethereum-like Secp256k1 signatures, and another one is being proposed to
support Secp256r1 signatures for FIDO Passkeys.
Historically, the two precompiles were built at different times and
by different people, so naturally there are some subtle differences
in how they behave, especially in edge cases.
The main goal of this document is to provide a specification for how …
> SIMD-0152: Precompiles

- proposals/0153-elgamal-proof-program.md
Deprecate the existing ZK Token Proof program that is tailored for the SPL Token program and replace it with a more general zero-knowledge proof program called the ZK ElGamal Proof program.
The existing native ZK Token Proof program contains logic that is quite specialized for the SPL Token program. This program is a native built-in program that is part of the validator. These type of programs should generally not favor any specific application or program like the SPL Token program.
This document proposes to deprecate the existing ZK Token Proof program and replace it with a new program that is independent of any specific application.
> SIMD-0153: ZK ElGamal Proof program

- proposals/0148-stake-program-move-instructions.md
two new instructions for moving value between stake accounts without holding `Withdrawer`
> SIMD-0148: `MoveStake` and `MoveLamports` instructions

- proposals/0149-migrate-snapshot-epoch-stakes.md
Migrate bank snapshots to a new "epoch stakes" field in order to store
additional stake state needed for calculating partitioned rewards.
> SIMD-0149: Migrate Snapshot Epoch Stakes

- XXXX-template.md
The current template for SIMDs places the "Alternatives Considered" section before any details about the proposed design, including "Detailed Design" in particular.
This can be confusing for readers, since alternative designs usually reference the detailed design proposed in the "Detailed Design" section for contrast.
Move the "Alternatives Considered" section below "Detailed Design". With this setup, readers can consume the proposed design, then read the alternatives, after digesting the proposed design details. This should make the context much more clear when a reader reaches the "Alternatives Considered" section.
> template: move alternatives section below detailed design

- proposals/0215-accounts-lattice-hash.md
I was informed that @samkim-crypto was one of the original authors of the lattice hash SIMD, so adding him to the authors.
> SIMD-0215: Adds Sam Kim to authors

- .github/linter/customRules.ts
The header linter doesn't go through all the proposal headers when checking that the required headers are present. So if a proposal adds a custom header in the middle of the required headers, the linter will fail: https://github.com/solana-foundation/solana-improvement-documents/actions/runs/12943366763/job/36102577418
> Fix header linter

- proposals/0118-partitioned-epoch-reward-distribution.md
Testnet exposed a bug in the SIMD-118 implementation. That has been patched (to be released in Agave v2.0.9), and wrapped in a new superset feature gate. This PR updates the feature-gate details. The linked Agave feature issue retains the original feature ID.
> SIMD-118: update feature-gate info

- proposals/0191-enable-transaction-loading-failure-fees.md
This proposal was split out of #82 in order to simplify the review process and have a more tightly coupled SIMD-feature activation relationship.
> SIMD-0191: Relax Transaction Constraints - Loading Failures

- proposals/0175-disable-partitioned-rent-collection.md
- No longer require changes to the `rent_epoch` field. Simply disabling partitioned rent is enough.
- Add feature issue
> Amend SIMD-0175: Exclude rent_epoch field changes

- proposals/0215-accounts-lattice-hash.md
The Agave code implementing SIMD-215 did not match the actual SIMD text, so we need to update the code. Since the feature gate is already in a release (v2.2), we need to rekey it.
Refer to https://github.com/anza-xyz/agave/pull/5336 for more information.
> Rekeys SIMD-215

- proposals/0313-drop-unchained-merkle-shreds.md
Backfilling the SIMD for this feature https://github.com/anza-xyz/feature-gate-tracker/issues/80
> SIMD-0313: Drop unchained merkle shreds

- proposals/0317-enforce-32-data-shreds.md
All clients currently send 32 data + 32 coding shreds, however Turbine still allows to send and receive a variable number of shreds. With this change we will enforce sending and receiving only 32 data + 32 coding shreds.
> SIMD-0317: Enforce 32 data + 32 coding shreds
